#!/bin/bash
#SBATCH --job-name=a2
#SBATCH --output=logs/a2_%A.out
#SBATCH --error=logs/a2_%A.err
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:4
#SBATCH --mem=24G
#SBATCH --time=12:00:00

#uv run --no-sync python A2.py
uv run --no-sync python A2_qlora_v3.py